name: flutter_gradient_animation_text
description: Create an animated gradient text very easily by taking text, colors, and duration of animation as inputs.
version: 1.0.2
homepage: https://github.com/SahilDShaw/flutter-gradient-animation-text

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: