name: flutter_gradient_animation_text
description: GradientAnimationText helps to create a linear gradient animation over the text very easily. It takes the text string, a list of colors, and the duration of the animation as the arguments. The linear gradient can be transformed, the animation can be reversed, and the font size and weight can be set as desired as well.
version: 1.0.0
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: